# A General Framework for Linear Models

In [2]:
import sympy
from sympy import init_printing
import numpy as np
from numpy.linalg import inv

init_printing()
np.set_printoptions(precision=3, suppress=True)

A simple enlightment on the fact that
$$
    \Phi^T \Phi = \sum_{i=1}^{N} \phi(x_i) \phi(x_i)^T
$$

Consider
* $\Phi \in \mathbb{R}^{N\times M}$
* $\phi(x_i) \in \mathbb{R}^{M\times 1}$

Where
$$
    \Phi = \begin{bmatrix} \phi(x_1)^T \\ \vdots \\ \phi(x_N)^T \end{bmatrix}
$$

Thus,

$$
    \Phi^T\Phi = \begin{bmatrix} \phi(x_1) & \ldots & \phi(x_N) \end{bmatrix} \begin{bmatrix} \phi(x_1)^T \\ \vdots \\ \phi(x_N)^T \end{bmatrix} = \sum_{i=1}^{N} \phi(x_i) \phi(x_i)^T
$$

In [3]:
phi_01 = sympy.symbols('\phi_{0}(x_1)')
phi_02 = sympy.symbols('\phi_{0}(x_2)')

phi_11 = sympy.symbols('\phi_{1}(x_1)')
phi_12 = sympy.symbols('\phi_{1}(x_2)')

phi_21 = sympy.symbols('\phi_{2}(x_1)')
phi_22 = sympy.symbols('\phi_{2}(x_2)')

In [4]:
Phi = sympy.Matrix([
    [phi_01, phi_02],
    [phi_11, phi_12],
    [phi_21, phi_22]
])

In [5]:
# N: number of datapoints
# M: number of basis functions
Phi

⎡\phi_{0}(x_1)  \phi_{0}(x_2)⎤
⎢                            ⎥
⎢\phi_{1}(x_1)  \phi_{1}(x_2)⎥
⎢                            ⎥
⎣\phi_{2}(x_1)  \phi_{2}(x_2)⎦

In [6]:
E1 = Phi.T @ Phi
E1

⎡                                2                2                2          
⎢                   \phi_{0}(x_1)  + \phi_{1}(x_1)  + \phi_{2}(x_1)           
⎢                                                                             
⎢                                                                             
⎣\phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{2}(x_1)⋅\ph

                                                                              
            \phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{
                                                                              
                                            2                2                
i_{2}(x_2)                     \phi_{0}(x_2)  + \phi_{1}(x_2)  + \phi_{2}(x_2)

                     ⎤
2}(x_1)⋅\phi_{2}(x_2)⎥
                     ⎥
2                    ⎥
                     ⎦

In [7]:
phi_0 = sympy.Matrix([[phi_01, phi_02]]).T
phi_1 = sympy.Matrix([[phi_11, phi_12]]).T
phi_2 = sympy.Matrix([[phi_21, phi_22]]).T

In [8]:
E2 = phi_0 @ phi_0.T + phi_1 @ phi_1.T + phi_2 @ phi_2.T
E2

⎡                                2                2                2          
⎢                   \phi_{0}(x_1)  + \phi_{1}(x_1)  + \phi_{2}(x_1)           
⎢                                                                             
⎢                                                                             
⎣\phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{2}(x_1)⋅\ph

                                                                              
            \phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{
                                                                              
                                            2                2                
i_{2}(x_2)                     \phi_{0}(x_2)  + \phi_{1}(x_2)  + \phi_{2}(x_2)

                     ⎤
2}(x_1)⋅\phi_{2}(x_2)⎥
                     ⎥
2                    ⎥
                     ⎦

In [9]:
E1 == E2

True

# 最小二乗法の幾何学的表現

In [10]:
def pseudoinverse(phi):
    return inv(phi.T @ phi) @ phi.T

In [11]:
N, M = 7, 5
Phi = np.random.randn(N, M)
Phi @ pseudoinverse(Phi)

array([[ 0.819, -0.155, -0.295,  0.069, -0.117,  0.044,  0.129],
       [-0.155,  0.517, -0.087,  0.432, -0.122, -0.051, -0.119],
       [-0.295, -0.087,  0.44 , -0.064, -0.179,  0.114,  0.32 ],
       [ 0.069,  0.432, -0.064,  0.577,  0.068,  0.078,  0.195],
       [-0.117, -0.122, -0.179,  0.068,  0.924,  0.023,  0.069],
       [ 0.044, -0.051,  0.114,  0.078,  0.023,  0.967, -0.09 ],
       [ 0.129, -0.119,  0.32 ,  0.195,  0.069, -0.09 ,  0.756]])

In [12]:
v = np.array([2, 1, 4, 1, 5, 7, 1]).reshape(-1, 1)
v

array([[2],
       [1],
       [4],
       [1],
       [5],
       [7],
       [1]])

In [13]:
Phi @ pseudoinverse(Phi) @ v

array([[ 0.224],
       [-0.797],
       [ 1.238],
       [ 1.974],
       [ 3.84 ],
       [ 7.361],
       [ 2.086]])

# 複数の出力

In [ ]:
w11, w12, w21, w22 = sympy.symbols("w_{11}, w_{12}, w_{21}, w_{22}")
x1, x2 = sympy.symbols("x_1 x_2")

W = sympy.Matrix([
    [w11, w12],
    [w21, w22]
])
x = sympy.Matrix([[x1, x2]]).T

In [14]:
w11, w12, w21, w22 = sympy.symbols('w_{11}, w_{12}, w_{21}, w_[22]')
x1, x2 = sympy.symbols('x_1 x_2')

W = sympy.Matrix([
    [w11, w12],
    [w21, w22]
])
x = sympy.Matrix([[x1, x2]]).T

In [15]:
((W.T @ x).T @ (W.T @ x))[0]

In [16]:
(W.T @ x) @ x.T

⎡x₁⋅(w_{11}⋅x₁ + w_{21}⋅x₂)  x₂⋅(w_{11}⋅x₁ + w_{21}⋅x₂)⎤
⎢                                                      ⎥
⎣x₁⋅(w_[22]⋅x₂ + w_{12}⋅x₁)  x₂⋅(w_[22]⋅x₂ + w_{12}⋅x₁)⎦